spring.application.name=finpulse

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

app.jwt.secret=F!nPu1s3-S3cr3t-K3y-Change-In-Prod-32chars
app.jwt.expiration-ms=86400000